### PR TITLE
path and typo fixes

### PR DESCRIPTION
**Pull request by pbek**
Thank you for the great library, I'm using it in <https://github.com/pbek/QOwnNotes>!
If you like pull requests, here are some fixes I made.

### CODE REVIEW

**Comment by iamantony** [comment]
Hi! Thank you for your contribution!

I could merge only one commit - fixed a typo (7650682).
I am not sure about your second commit (a9bee37). It seems to me that those changes are only specific to your project QOwnNotes.

**Comment by pbek** [comment]
The 2nd commit could be dangerous, but your project file built with the changes... I wonder why it can be built without them. :)

**Comment by iamantony** [comment]
Build for 7650682 failed because Stephan Binner made some changes in his Qt repo. I updated my .travis.yml file so now there should be no build problems.

Commit db3e9a8. Well... man, you do it wrong :smile: . 
qtcsv is a Shared Library. It is assumed that the library is compiled into *.so file on Linux or *.dll on Windows. When some application want to use functionality from shared library, it dynamically loads library file into memory so it could reach libraries' functions.

QTCSVSHARED_EXPORT - is a macro, that help to declare public functionality/symbols (classes, functions, variables and so on) of the library. [This article](http://doc.qt.io/qt-5/sharedlibrary.html#using-symbols-from-shared-libraries) explains how Qt generates this macro. And in [this article](http://blog.fesnel.com/blog/2009/08/19/hiding-whats-exposed-in-a-shared-library/) author explains basic idea why it is useful to hide unnecessary symbols in the shared library and how to do it.

Why you have build problems with QTCSVSHARED_EXPORT in QOwnNotes? You do not use qtcsv as a shared library. You embed some of the qtcsv sources into your app so that they become part of the QOwnNotes.exe, not a qtcsv.dll library. Is it legitimate? Absolutely yes. Should you remove QTCSVSHARED_EXPORT from source files in [your fork of qtcsv](https://github.com/pbek/qtcsv)? Yes, because this macro is useless in your case. Also you can remove qtcsv_global.h where QTCSVSHARED_EXPORT declared.

So, finally. I could merge only 7650682 commit. It is in master branch with id 984e718895ccc050273b4f00e7494d0c84ce61f0.

Again, thank you @pbek!!

**Comment by pbek** [comment]
> Stephan Binner made some changes in his Qt repo

I also had to switch to another Qt version ;)

> Well... man, you do it wrong 

Most certainly I did, because I wasn't able to build and deploy the library as shared library under Linux, macOS and Windows with qmake and cmake...
So in the end I removed `QTCSVSHARED_EXPORT` altogether, because I saw no point in building it as shared library, that only made troubles for me so far ;)

**Pull request closed without merging**
